platform: linux
image_resource:
  type: registry-image
  source:
    repository: mattcl/aoc-ci-bencher
    tag: latest

inputs:
  - name: ci
  - name: aoc-tools
  - name: aoc-inputs-write
  - name: repo

params:
  PARTICIPANT:
  INSTALL: ""
  # this one is relative because we'll be in the repo while checking
  AOC_TOOLS_CONFIG: "../ci/2025/config.toml"
  YEAR: "2025"

run:
  path: ((check-input-script))
