platform: linux
image_resource:
  type: registry-image
  source:
    repository: mattcl/aoc-ci-bencher
    tag: latest

inputs:
  - name: ci
  - name: aoc-tools
  - name: aoc-inputs
  - name: aoc-inputs-write
  - name: mattcl
  - name: mattcl-py
  - name: lanjian
  # - name: kcen
  # - name: mikofo

outputs:
  - name: aoc-inputs-write

params:
  AOC_TOOLS_CONFIG: "ci/2025/config.toml"
  YEAR: "2025"

run:
  path: ci/scripts/collect-inputs.sh
