platform: linux
image_resource:
  type: registry-image
  source:
    # TODO: Consider updating aoc-bencher to Debian trixie (so this #just_works on nim 2.2.4)
    repository: nimlang/nim
    tag: 2.2.4-alpine-regular

inputs:
  - name: ci
  - name: repo

outputs:
  - name: repo

run:
  dir: repo
  path: ../ci/2025/scripts/kcen-build.sh
