platform: linux
image_resource:
  type: registry-image
  source:
    repository: mattcl/ci-rust-slim
    tag: 1.91

inputs:
  - name: ci
  - name: repo

outputs:
  - name: repo

caches:
  # yeah, I'm not sure how I feel about caching the registry like this,
  # but concourse only allows relative paths instead of absolute ones
  - path: ../../../usr/local/cargo/registry

  # cache the target folder to speed up builds
  - path: repo/target

run:
  dir: repo
  path: ../ci/2024/scripts/lanjian-build.sh
