platform: linux
image_resource:
  type: registry-image
  source:
    repository: bitnami/git
    tag: latest

inputs:
  - name: ci
  - name: repo

outputs:
  - name: release

params:
  TARGET: "x86_64-unknown-linux-musl"

run:
  path: ci/2025/scripts/lanjian-package.sh
